-- Copyright 2021 Google LLC
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- This SQL extracts all info from the DBC.QryLogV table except for ElapsedTime,
-- ErrorText and TDWMMSRCount.
SELECT
  AbortFlag AS "AbortFlag",
  AcctString AS "AcctString",
  AcctStringDate AS "AcctStringDate",
  AcctStringHour AS "AcctStringHour",
  AcctStringTime AS "AcctStringTime",
  AMPCPUTime AS "AMPCPUTime",
  AMPCPUTimeNorm AS "AMPCPUTimeNorm",
  AppID AS "AppID",
  CacheFlag AS "CacheFlag",
  CalendarName AS "CalendarName",
  CallNestingLevel AS "CallNestingLevel",
  CheckpointNum AS "CheckpointNum",
  ClientAddr AS "ClientAddr",
  ClientID AS "ClientID",
  CollectTimeStamp AT TIME ZONE INTERVAL '0:00' HOUR TO MINUTE AS "CollectTimeStamp",
  CPUDecayLevel AS "CPUDecayLevel",
  DataCollectAlg AS "DataCollectAlg",
  DBQLStatus AS "DBQLStatus",
  DefaultDatabase AS "DefaultDatabase",
  DelayTime AS "DelayTime",
  DisCPUTime AS "DisCPUTime",
  DisCPUTimeNorm AS "DisCPUTimeNorm",
-- The "Inverval" type is not fully supported yet.
--  ElapsedTime AS "ElapsedTime",
  ErrorCode AS "ErrorCode",
-- jdbc would throw an error if we add ErrorText in the query.
--  ErrorText AS "ErrorText",
  EstMaxRowCount AS "EstMaxRowCount",
  EstMaxStepTime AS "EstMaxStepTime",
  EstProcTime AS "EstProcTime",
  EstResultRows AS "EstResultRows",
  ExpandAcctString AS "ExpandAcctString",
  FirstRespTime AT TIME ZONE INTERVAL '0:00' HOUR TO MINUTE AS "FirstRespTime",
  FirstStepTime AT TIME ZONE INTERVAL '0:00' HOUR TO MINUTE AS "FirstStepTime",
  FlexThrottle AS "FlexThrottle",
  ImpactSpool AS "ImpactSpool",
  InternalRequestNum AS "InternalRequestNum",
  IODecayLevel AS "IODecayLevel",
  IterationCount AS "IterationCount",
  KeepFlag AS "KeepFlag",
  LastRespTime AS "LastRespTime",
  LockDelay AS "LockDelay",
  LockLevel AS "LockLevel",
  LogicalHostID AS "LogicalHostID",
  LogonDateTime AT TIME ZONE INTERVAL '0:00' HOUR TO MINUTE AS "LogonDateTime",
  LogonSource AS "LogonSource",
  LSN AS "LSN",
  MaxAMPCPUTime AS "MaxAMPCPUTime",
  MaxAMPCPUTimeNorm AS "MaxAMPCPUTimeNorm",
  MaxAmpIO AS "MaxAmpIO",
  MaxCPUAmpNumber AS "MaxCPUAmpNumber",
  MaxCPUAmpNumberNorm AS "MaxCPUAmpNumberNorm",
  MaxIOAmpNumber AS "MaxIOAmpNumber",
  MaxNumMapAMPs AS "MaxNumMapAMPs",
  MaxOneMBRowSize AS "MaxOneMBRowSize",
  MaxStepMemory AS "MaxStepMemory",
  MaxStepsInPar AS "MaxStepsInPar",
  MinAmpCPUTime AS "MinAmpCPUTime",
  MinAmpCPUTimeNorm AS "MinAmpCPUTimeNorm",
  MinAmpIO AS "MinAmpIO",
  MinNumMapAMPs AS "MinNumMapAMPs",
  MinRespHoldTime AS "MinRespHoldTime",
  NumFragments AS "NumFragments",
  NumOfActiveAMPs AS "NumOfActiveAMPs",
  NumRequestCtx AS "NumRequestCtx",
  NumResultOneMBRows AS "NumResultOneMBRows",
  NumResultRows AS "NumResultRows",
  NumSteps AS "NumSteps",
  NumStepswPar AS "NumStepswPar",
  ParamQuery AS "ParamQuery",
  ParserCPUTime AS "ParserCPUTime",
  ParserCPUTimeNorm AS "ParserCPUTimeNorm",
  ParserExpReq AS "ParserExpReq",
  PersistentSpool AS "PersistentSpool",
  ProcID AS "ProcID",
  ProfileID AS "ProfileID",
  ProfileName AS "ProfileName",
  ProxyRole AS "ProxyRole",
  ProxyUser AS "ProxyUser",
  ProxyUserID AS "ProxyUserID",
  QueryBand AS "QueryBand",
  QueryID AS "QueryID",
  QueryRedriven AS "QueryRedriven",
  QueryText AS "QueryText",
  ReDriveKind AS "ReDriveKind",
  RemoteQuery AS "RemoteQuery",
  ReqIOKB AS "ReqIOKB",
  ReqPhysIO AS "ReqPhysIO",
  ReqPhysIOKB AS "ReqPhysIOKB",
  RequestMode AS "RequestMode",
  RequestNum AS "RequestNum",
  SeqRespTime AS "SeqRespTime",
  SessionID AS "SessionID",
  SessionTemporalQualifier AS "SessionTemporalQualifier",
  SpoolUsage AS "SpoolUsage",
  StartTime AT TIME ZONE INTERVAL '0:00' HOUR TO MINUTE AS "StartTime",
  StatementGroup AS "StatementGroup",
  Statements AS "Statements",
  StatementType AS "StatementType",
  SysDefNumMapAMPs AS "SysDefNumMapAMPs",
  TacticalCPUException AS "TacticalCPUException",
  TacticalIOException AS "TacticalIOException",
  TDWMEstMemUsage AS "TDWMEstMemUsage",
-- TDWMMSRCount is not found in the table.
--  TDWMMSRCount AS "TDWMMSRCount",
  ThrottleBypassed AS "ThrottleBypassed",
  TotalFirstRespTime AS "TotalFirstRespTime",
  TotalIOCount AS "TotalIOCount",
  TotalServerByteCount AS "TotalServerByteCount",
  TTGranularity AS "TTGranularity",
  TxnMode AS "TxnMode",
  TxnUniq AS "TxnUniq",
  UnitySQL AS "UnitySQL",
  UnityTime AS "UnityTime",
  UsedIota AS "UsedIota",
  UserID AS "UserID",
  UserName AS "UserName",
  UtilityByteCount AS "UtilityByteCount",
  UtilityInfoAvailable AS "UtilityInfoAvailable",
  UtilityRowCount AS "UtilityRowCount",
  VHLogicalIO AS "VHLogicalIO",
  VHLogicalIOKB AS "VHLogicalIOKB",
  VHPhysIO AS "VHPhysIO",
  VHPhysIOKB AS "VHPhysIOKB",
  WarningOnly AS "WarningOnly",
  WDName AS "WDName"
FROM DBC.QryLogV